In [6]:
import random
import numpy as np
import time

n = 100
m = 100
mat_a = [[random.randint(1, 1000) for e in range(n)] for e in range(m)]

mat_b = [[random.randint(1, 1000) for e in range(n)] for e in range(m)]

mat_c = [[random.randint(0, 0) for e in range(n)] for e in range(m)]
start = time.time()
for i in range(n):
    for j in range(len(mat_b[0])):
        for k in range(len(mat_b)):
            mat_c[i][j] += mat_a[i][k] * mat_b[k][i]
end = time.time()

In [2]:
print("Matrix A: ")
for a in mat_a:
    print(a)

Matrix A: 
[156, 757, 860, 789, 1, 3, 417, 107, 991, 168, 782, 377, 683, 441, 333, 475, 379, 782, 224, 465, 280, 816, 914, 205, 963, 510, 404, 321, 435, 468, 574, 32, 663, 328, 990, 195, 837, 92, 276, 231, 396, 386, 984, 832, 411, 658, 319, 993, 437, 411, 127, 564, 34, 731, 166, 181, 893, 519, 867, 67, 990, 549, 497, 506, 663, 982, 267, 815, 48, 913, 867, 775, 604, 168, 855, 603, 371, 872, 37, 354, 141, 982, 122, 426, 599, 999, 813, 435, 797, 597, 708, 669, 531, 82, 193, 192, 288, 222, 274, 989]
[220, 600, 147, 3, 549, 252, 742, 809, 384, 784, 960, 198, 545, 519, 273, 501, 561, 911, 179, 529, 485, 659, 180, 583, 709, 639, 383, 119, 220, 502, 733, 958, 975, 546, 613, 622, 485, 20, 765, 517, 74, 996, 611, 312, 585, 428, 15, 545, 915, 676, 276, 869, 631, 113, 972, 880, 50, 520, 601, 905, 754, 585, 291, 943, 447, 765, 785, 792, 482, 472, 699, 167, 225, 366, 584, 716, 817, 845, 978, 215, 950, 344, 5, 801, 463, 167, 425, 529, 66, 224, 743, 247, 181, 561, 176, 62, 62, 232, 431, 864]
[351, 607

In [3]:
print("\n Matrix B: ")
for b in mat_b:
    print(b)


 Matrix B: 
[721, 953, 820, 750, 395, 107, 564, 975, 977, 422, 196, 801, 932, 398, 513, 417, 226, 156, 520, 503, 513, 651, 693, 347, 332, 474, 175, 761, 574, 955, 677, 386, 770, 363, 720, 406, 293, 450, 716, 574, 235, 441, 883, 41, 608, 228, 303, 98, 507, 572, 701, 237, 517, 476, 719, 749, 217, 935, 851, 570, 390, 875, 255, 79, 337, 56, 550, 697, 218, 921, 790, 687, 875, 870, 175, 589, 996, 591, 204, 836, 392, 142, 556, 161, 879, 815, 434, 140, 426, 717, 121, 23, 831, 156, 634, 52, 251, 362, 17, 340]
[692, 654, 509, 268, 9, 800, 107, 546, 99, 108, 649, 283, 525, 560, 777, 565, 411, 347, 210, 529, 861, 10, 180, 498, 400, 192, 916, 242, 518, 215, 394, 559, 242, 268, 220, 195, 765, 155, 796, 846, 503, 710, 290, 555, 783, 331, 468, 881, 824, 412, 362, 96, 143, 11, 432, 762, 939, 832, 876, 125, 726, 682, 441, 811, 875, 871, 861, 11, 112, 423, 207, 719, 372, 554, 88, 896, 176, 638, 877, 449, 322, 825, 81, 785, 680, 644, 861, 428, 977, 35, 319, 333, 878, 158, 496, 554, 850, 344, 250, 331]
[5

In [4]:
print("\n Result:")
for c in mat_c:
    print(c)


 Result:
[23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433, 23294433,

In [5]:
print("\n Time of execution: ", end - start)


 Time of execution:  2.197530746459961


In [7]:
print("\n\t\t Numpy")
a = np.array(mat_a)
b = np.array(mat_b)
print("\n Matrix A: ")
print(a)
print("\n Matrix B: ")
print(b)
print("\n Result: ")
start_np = time.time()
c = a.dot(b)
end_np = time.time()
print(c)
print("\n Time of execution: ", end_np - start_np)


		 Numpy

 Matrix A: 
[[844 793 606 ... 763 357 527]
 [905 627 816 ... 807 985 336]
 [861 302 228 ... 772 503 132]
 ...
 [448  57 750 ...  69 764 652]
 [903 608 480 ... 334 707 509]
 [174 381 668 ... 771 340 549]]

 Matrix B: 
[[378 406  71 ... 990  72 788]
 [538 705 986 ... 587  22 244]
 [272 368 901 ... 543 598 200]
 ...
 [746  30 509 ... 440 831 749]
 [660 651 885 ... 271 731  92]
 [905 327 104 ... 108 881  77]]

 Result: 
[[24115281 22412252 23994322 ... 21499283 23436949 25681198]
 [24942349 23625581 26450014 ... 24251342 24649735 27848551]
 [23886289 22154034 22719336 ... 22335289 23104696 25251735]
 ...
 [25523371 24845161 24929647 ... 24540895 25306234 26856861]
 [26913227 23335605 26448035 ... 24925393 26123298 30324106]
 [23345212 22921449 25497083 ... 23715693 27936602 26229503]]

 Time of execution:  0.006005048751831055
